### ISSUE TITLE
CHAPTER 5 Try It Yourself no.3 Answer Review

### ISSUE THREAD

**Issue by tomyfalgui** [anthonydb/practical-sql#7]
```SQL
SELECT
  percentile_cont(.5)
  WITHIN GROUP (ORDER BY (
    SELECT
      p0010001
    WHERE state_us_abbreviation = 'CA'
  )) AS "CA State Median",
  percentile_cont(.5)
  WITHIN GROUP (ORDER BY (
    SELECT p0010001
    WHERE state_us_abbreviation = 'NY'
  )) AS "NY State Median"
FROM us_counties_2010;
```

Is this a valid solution? Do you have a better solution in mind?

**Comment by anthonydb** [comment]
@tomyfalgui 
That is an accurate and well-constructed solution! In fact, it's better than the solution I suggested in the solution file https://github.com/anthonydb/practical-sql/blob/master/Try_It_Yourself/Try_It_Yourself.sql#L245 because it provides the answers in a single query rather than two separate queries. 

With your permission, I will include your query in the solutions file (with credit).

**Comment by tomyfalgui** [comment]
You may! Thanks for responding so quickly.
